---

####
####
#### Run on PR
####
####

kind: pipeline
type: kubernetes
name: Run CI stack

trigger:
  event:
    include:
    - pull_request

steps:
  - name: npm-install
    image: node:12
    depends_on: [ clone ] 
    commands:
      - npm install

  - name: Lint Typescript
    image: node:12
    depends_on: [ npm-install ] 
    commands:
      - npm run lint

  - name: Type checking
    image: node:12
    depends_on: [ npm-install ] 
    commands:
      - npm run tsc


  - name: Units Tests
    image: node:12
    depends_on: [ npm-install ] 
    commands:
      # - MONGO_HOST=mongo REDIS_HOST=redis RABBITMQ_HOST=rabbitmq npm run test:ci
      - MONGO_HOST=mongo REDIS_HOST=redis npm run test:ci

services:
- name: redis
  image: redis
# - name: rabbitmq
#   image: rabbitmq
- name: mongo
  image: mongo

---
kind: pipeline
name: Build&Push image

trigger:
  branch:
  - "*"
  event:
  - push

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: komakio/backend
    tags: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

- name: git deploy
  image: bitnami/git
  commands:
  - git clone "https://$(echo $githubUsername):$(echo $githubPassword)@github.com/wikibusiness/komak-k8s.git"
  - cd komak-k8s
  - rm -f src/backend-version.yaml
  - "echo 'imageTag: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' > src/backend-version.yaml"
  - "git add . && git commit -a -m 'Updated backend to tag ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' && git push"

  environment:
    githubUsername:
      from_secret: GITHUB_USERNAME
    githubPassword:
      from_secret: GITHUB_PASSWORD

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: errors
  when:
    status: [ failure ]
---
#####################
# PROD DEPLOYMENT
#####################
kind: pipeline
name: Build&Push production

trigger:
  event:
  - tag

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: komakio/backend
    tags: ${DRONE_TAG}

- name: git deploy
  image: bitnami/git
  commands:
  - git clone "https://$(echo $githubUsername):$(echo $githubPassword)@github.com/wikibusiness/komak-k8s.git"
  - cd komak-k8s
  - rm -f src/backend-production-version.yaml
  - "echo 'imageTag: \"${DRONE_TAG}\"' > src/backend-production-version.yaml"
  - "git add . && git commit -a -m 'Updated production backend to tag ${DRONE_TAG}' && git push"

  environment:
    githubUsername:
      from_secret: GITHUB_USERNAME
    githubPassword:
      from_secret: GITHUB_PASSWORD

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    template: >
      {{#success build.status}}
        Production deployment (backend) {{build.tag}} succeeded.
      {{else}}
        Backend production build {{build.number}} failed. Fix me please.
      {{/success}}
---
kind: signature
hmac: f3bd75857e648cfbc73b51d2c01b3cf623ff380de67ee122d51d6f74a403e4cf

...
