kind: pipeline
name: Build&Push image

trigger:
  branch:
  - drone
  - master
  event:
  - push

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: komakio/backend
    tags: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

- name: git deploy
  image: bitnami/git
  environment:
    GITHUB_USERNAME:
      from_secret: GITHUB_USERNAME
    GITHUB_PASSWORD:
      from_secret: GITHUB_PASSWORD
  commands:
  - git clone https://${GITHUB_PASSWORD}:x-oauth-basic@github.com/wikibusiness/komak-k8s.git
  - rm -f komak-k8/backend-version.yaml
  - echo "imageTag: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}" komak-k8/backend-version.yaml
  - cd komak-k8s && git add . && git commit -a -m "Updated backend to tag ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}" && git push